import React, { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import type { Bundle } from '../server/evidence';
import type { Frame } from '../server/schema';
import './styles.css';
import { MemeHero, LaunchPath } from './identity';
type Summary={id:string;state:string;provenance:string;created_at:string;kind:string;stimulus_hz:number;silence_output:boolean};
type Detail=Bundle&{verification:{status:string}};
async function get<T>(path:string):Promise<T>{const r=await fetch(path);if(!r.ok)throw new Error('Evidence could not be loaded from the local controller. No result is confirmed.');return r.json();}
const human=(s:string)=>s.replaceAll('_',' ');
const short=(s:string)=>s.slice(0,10)+'…'+s.slice(-6);

function Signal({frames,cursor,duration,output}:{frames:Frame[];cursor:number;duration:number;output:string[]}) {
  const visible=frames.slice(0,cursor+1);
  const ids=Array.from(new Set(frames.flatMap(f=>f.spikes.map(s=>s.neuron_id)))).sort();
  const rows=ids.slice(0,80), index=new Map(rows.map((id,i)=>[id,i]));
  const spikes=visible.flatMap(f=>f.spikes).filter(s=>index.has(s.neuron_id));
  return <svg className="raster" viewBox="0 0 800 330" role="img" aria-label="Recorded spike raster. Horizontal axis simulation time, rows active neuron IDs.">
    {[0,1,2,3,4,5].map(i=><g key={i}><line x1={48+i*140} y1="20" x2={48+i*140} y2="285" className="gridline"/><text x={48+i*140} y="315">{duration*i/5} ms</text></g>)}
    {[0,1,2,3,4].map(i=><line key={i} x1="48" y1={25+i*64} x2="748" y2={25+i*64} className="gridline"/>)}
    {spikes.map((s,i)=><line key={i} x1={48+s.t_us/(duration*1000)*700} x2={48+s.t_us/(duration*1000)*700} y1={25+(index.get(s.neuron_id)||0)/Math.max(rows.length,1)*250} y2={29+(index.get(s.neuron_id)||0)/Math.max(rows.length,1)*250} stroke={output.includes(s.neuron_id)?'#dff17c':'#929fa3'} strokeWidth="1.4"/>)}
    <line x1={48+((visible.at(-1)?.t_ms||0)+10)/duration*700} x2={48+((visible.at(-1)?.t_ms||0)+10)/duration*700} y1="20" y2="285" stroke="#dff17c" opacity=".7"/>
    {!spikes.length&&<text x="400" y="165" textAnchor="middle">No spikes in this interval</text>}
  </svg>;
}
function App(){
  const [runs,setRuns]=useState<Summary[]>([]),[selected,setSelected]=useState(new URLSearchParams(location.search).get('run')||''),[detail,setDetail]=useState<Detail|null>(null);
  const [listError,setListError]=useState(''),[detailError,setDetailError]=useState(''),[cursor,setCursor]=useState(0),[playing,setPlaying]=useState(false);
  useEffect(()=>{let alive=true;const load=()=>get<Summary[]>('/api/runs').then(r=>{if(alive){setRuns(r);setSelected(s=>s||r.find(x=>x.provenance==='SHIU_REFERENCE'&&x.state!=='INVALID')?.id||r[0]?.id||'');setListError('');}}).catch(e=>{if(alive)setListError(e.message);});load();const t=setInterval(load,3000);return()=>{alive=false;clearInterval(t);};},[]);
  useEffect(()=>{if(!selected)return;let alive=true;setDetail(null);setPlaying(false);const load=()=>get<Detail>('/api/runs/'+selected).then(d=>{if(alive){setDetail(d);setDetailError('');}}).catch(e=>{if(alive)setDetailError(e.message);});load();const t=setInterval(load,3000);return()=>{alive=false;clearInterval(t);};},[selected]);
  const error=listError||detailError;
  const frames=(detail?.artifacts.find(a=>a.name==='frames')?.value||detail?.events.filter(e=>e.type==='frame')||[]) as Frame[];
  useEffect(()=>{setCursor(Math.max(0,frames.length-1));},[selected,frames.length]);
  useEffect(()=>{if(!playing)return;const t=setInterval(()=>setCursor(c=>{if(c>=frames.length-1){setPlaying(false);return c;}return c+1;}),70);return()=>clearInterval(t);},[playing,frames.length]);
  const m=detail?.run.manifest,result=detail?.artifacts.find(a=>a.name==='runner_result')?.value;
  const decision=detail?.artifacts.find(a=>a.name==='decision')?.value,preview=detail?.artifacts.find(a=>a.name==='preview')?.value;
  const isMock=m?.runner==='MOCK',counts=(decision?.counts||[]) as number[], now=frames[cursor];
  return <><div className="edge-tape edge-left" aria-hidden="true">BELLFLY · LET THE FLY RING THE BELL · BELLFLY · LET THE FLY RING THE BELL · BELLFLY · LET THE FLY RING THE BELL</div><div className="edge-tape edge-right" aria-hidden="true">BELLFLY · TINY BRAIN. BIG LAUNCH. · BELLFLY · TINY BRAIN. BIG LAUNCH. · BELLFLY · TINY BRAIN. BIG LAUNCH.</div><div className="safety"><span className="dot"/> BELLFLY / PRELAUNCH <span className="safety-right">NO TOKEN YET · LOCAL DEMO</span></div>
    <header><a className="brand" href="#">BELLFLY<span><small>PROVISIONAL NAME</small></span></a><nav><a href="#experiment">The fly</a><a href="#signal">Brain activity</a><a href="#launch">Launch plan</a><a href="#evidence">Proof ↗</a></nav></header>
    <main><MemeHero/>
    <div className="principle"><span>01 / INPUT</span> Fixed sugar stimulus <b>→</b><span>02 / MODEL</span> Recorded spikes <b>→</b><span>03 / RULE</span> Launch signal or no launch <b>→</b><span>04 / ADAPTER</span> Offline preview only</div>
    {error&&<div className="error" role="alert">{error} Previously loaded data may be stale.</div>}
    <section className="lab" id="signal"><div className="section-heading"><div><div className="eyebrow">INSIDE THE FLY</div><h2>Proof of buzz.</h2></div><label className="run-picker">Recorded rehearsal<select value={selected} onChange={e=>setSelected(e.target.value)} aria-label="Recorded rehearsal">{!runs.some(r=>r.id===selected)&&<option value={selected}>Record unavailable</option>}{runs.map(r=><option key={r.id} value={r.id}>{r.provenance} · {r.stimulus_hz} Hz{r.silence_output ? ' / MN9 ablation test' : ''} · {r.state} · {r.id.slice(0,8)}</option>)}</select></label></div>
    {!m?<div className="empty">{error?'Evidence unavailable. No outcome is confirmed.':runs.length?'Loading the recorded evidence…':'No rehearsals yet. Start one with npm run demo in the local terminal.'}</div>:<><div className="scope"><span className={'badge '+(isMock?'mock':'real')}>{isMock?'MOCK / SYNTHETIC':'REAL MODEL / ENGINEERING REHEARSAL'}</span><p>{isMock?'Synthetic test fixture. No connectome loaded.':'Shiu reference implementation · FlyWire v630 · modern Python/Brian2 environment; scientific equivalence pending.'}<br/>Stimulus: {m.stimulus.hz} Hz · MN9 incoming connections verified as disconnected: {result?.ablated_connections ?? 'not recorded'}.</p></div>{detail?.verification.status!=='VERIFIED_LOCAL' && <p className="error">This record is incomplete or cannot be verified by the current verifier. It is not a confirmed result.</p>}
    <div className="dashboard"><div className="signal-panel"><div className="panel-head"><span>SPIKE RASTER</span><span className="lime">{playing?'RECORDED PLAYBACK':'RECORDED DATA'} · {(now?.t_ms||0)+(now?10:0)} / {m.duration_ms} ms</span></div><Signal frames={frames} cursor={cursor} duration={m.duration_ms} output={m.rule.output_ids}/><div className="playback"><button disabled={!frames.length} onClick={()=>{if(cursor===frames.length-1)setCursor(0);setPlaying(!playing);}}>{playing?'Ⅱ Pause':'▶ Play recording'}</button><input aria-label="Recording position" type="range" min="0" max={Math.max(frames.length-1,0)} value={cursor} onChange={e=>{setPlaying(false);setCursor(Number(e.target.value));}}/><span>{frames.length} bins</span></div><p className="plot-note">Each mark is an exported spike. First 80 active neuron IDs, sorted by ID; full raster in evidence. No anatomical positions are implied.</p></div>
    <aside className="decision-panel"><div className="eyebrow">NEURAL OUTCOME</div><h3>{error ? 'UNAVAILABLE' : human(detail!.run.state)}</h3><p>{detail!.run.state==='LAUNCH_SIGNAL'?'The recorded signal met the frozen rule. This is not a token issuance.':detail!.run.state==='NO_LAUNCH'?'The full simulation window ended without meeting the bell rule.':detail!.run.state==='INVALID'?'The rehearsal failed validation. No emission was requested.':'The controller has not recorded a final outcome.'}</p><div className="output-meter"><span>MN9 output · current bin</span><strong>{counts[cursor]??'—'} <small>spikes</small></strong><div className="bars">{counts.map((n,i)=><i key={i} style={{height:`${Math.min(100,8+n*18)}%`,opacity:i<=cursor?1:.2}}/>)}</div></div><div className="deploy-state"><span>DEPLOYMENT</span><b>DISARMED</b><small>{preview?'Offline preview recorded':'Preview not available'} · no onchain receipt</small></div></aside></div>
    <div className="metrics"><div><span>Neurons loaded</span><strong>{result?.neurons_loaded?.toLocaleString()??'—'}</strong></div><div><span>Connection rows loaded</span><strong>{result?.connections_loaded?.toLocaleString()??'—'}</strong></div><div><span>Runner wall time</span><strong>{result?`${(result.elapsed_ms/1000).toFixed(2)} s`:'—'}</strong></div><div><span>Peak runner RAM</span><strong>{result?.peak_rss_bytes?`${(result.peak_rss_bytes/1048576).toFixed(0)} MiB`:'Not measured'}</strong></div></div></>}
    </section>
    <LaunchPath/>
    <section className="rules" id="rules"><div><div className="eyebrow">THE RULE COMES FIRST</div><h2>One question.<br/>Three possible answers.</h2><p>The fly does not choose a chain, a ticker or a supply. We define the interpretation of its output before running the model.</p><p>It is a simulation of neural dynamics, without a claim of consciousness or financial understanding.</p></div><div className="rule-list"><article><span>01</span><div><h3>LAUNCH SIGNAL</h3><p>{m?`At least ${m.rule.min_spikes} MN9 spike in each of ${m.rule.consecutive_bins} consecutive ${m.bin_ms} ms bins.`:'A fixed neural output rule must be met.'} The engineering threshold is provisional and not scientifically calibrated.</p></div></article><article><span>02</span><div><h3>NO LAUNCH</h3><p>A valid, complete window ends without meeting the rule. A quiet model is a valid negative result.</p></div></article><article><span>03</span><div><h3>INVALID</h3><p>Missing data, a mismatch, an interrupted process or a timeout. A technical failure never defaults to launch.</p></div></article></div></section>
    <section id="evidence" className="evidence"><div className="section-heading"><div><div className="eyebrow">DON’T TAKE THE ANIMATION’S WORD FOR IT</div><h2>Inspect. Download. Replay.</h2></div>{detail&&!error&&<a className="download" href={`/api/runs/${selected}/evidence`}>Download evidence bundle ↓</a>}</div><div className="evidence-grid"><div><h3>Manifest commitment</h3><code title={detail?.run.manifest_hash}>{detail?short(detail.run.manifest_hash):'No manifest yet'}</code><p>Frozen locally before the run. This is not an independently published timestamp.</p></div><div><h3>Verification</h3><strong>{error?'BACKEND UNAVAILABLE':detail?.verification.status||'PENDING'}</strong><p>Artifact integrity and decoder recomputation. This is not a cryptographic proof of correct execution.</p></div><div><h3>Proposed launch route</h3><strong>Long → GOOGL</strong><p>Chain 4663. Separate unsigned preparation is under review; the checked factory was paused on 10 Sep. Historical manifests below retain their original terms.</p></div></div>{detail&&<details><summary>View frozen manifest and decision rule</summary><pre>{JSON.stringify(detail.run.manifest,null,2)}</pre></details>}</section>
    <section className="closing"><p>LET THE FLY<br/><em>RING THE BELL.</em></p><div>The experiment is the causal chain.<br/>The token is a possible consequence.<br/><b>Public execution has not happened.</b></div></section></main><footer><span>BELLFLY / PRELAUNCH EXPERIMENT</span><span>Built on published neuroscience. All launch terms are provisional.</span><a href="#">Back to top ↑</a></footer></>;
}
createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
